services:
  aggregating-publisher-webui:
    image: ghcr.io/lenni0451/aggregatingpublisher:latest
    container_name: aggregating-publisher
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app
    restart: unless-stopped
